CREATE TABLE t(id INT, val TEXT);
INSERT INTO t VALUES(1,"a;b;c");
INSERT INTO t VALUES(2,"d;e;f");
INSERT INTO t VALUES(3,"g;h;i");
INSERT INTO t VALUES(4,"multi
line
string;");
SELECT 1;SELECT 2;SELECT 3;SELECT 4;SELECT 5;SELECT 6;
SELECT 7;SELECT 8;SELECT 9;SELECT 10;